services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        DJANGO_VERSION: ${DJANGO_VERSION:-}
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./tests/app/bookstore:/code
    ports:
      - "127.0.0.1:8000:8000"
  seleniumfirefox:
    image: selenium/standalone-firefox:4.35
    container_name: ${CONTAINER_NAME_SELENIUM:-seleniumfirefox}
    shm_size: 2gb
    ports:
      - "127.0.0.1:4444:4444"
    volumes:
      - ./docker/firefox/upload-data:/uploads:ro
  testa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        DJANGO_VERSION: ${DJANGO_VERSION:-}
    container_name: ${CONTAINER_NAME_TEST:-test}
    environment:
      SELENIUM_HOSTNAME: seleniumfirefox
      SELENIUM_DJANGO_HOSTNAME: 'django'
      DJANGO_SUPERUSER_USERNAME: 'testuser'
      DJANGO_SUPERUSER_EMAIL: 'testuser@example.com'
      DJANGO_SUPERUSER_PASSWORD: 'PfTk2UIX9s1LJFPgiBihflbjC6Ur9'
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
    depends_on:
      - seleniumfirefox
      - django
